name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  main:
    name: >-
      ${{ matrix.os }} ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}-latest
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      TEST_QUEUE_WORKERS: 2
      TEST_QUEUE_VERBOSE: 1
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]
        # Lowest and Latest version.
        ruby: ['2.3', '3.0']

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: install dependencies
        run: bundle install --jobs 3 --retry 3 && bundle exec appraisal install
      - name: spec
        run: bundle exec appraisal rake
